from random import choice, randint

extension = '.session.sql'

colors = [
    "Alice Blue",
    "Antique White",
    "Aqua",
    "Aquamarine",
    "Azure",
    "Beige",
    "Bisque",
    "Black",
    "Blanched Almond",
    "Blue",
    "Blue Violet",
    "Brown",
    "Burly Wood",
    "Cadet Blue",
    "Chartreuse",
    "Chocolate",
    "Coral",
    "Cornflower Blue",
    "Cornsilk",
    "Crimson",
    "Cyan",
    "Dark Blue",
    "Dark Cyan",
    "Dark Goldenrod",
    "Dark Gray",
    "Dark Green",
    "Dark Grey",
    "Dark Khaki",
    "Dark Magenta",
    "Dark Olive Green",
    "Dark Orange",
    "Dark Orchid",
    "Dark Red",
    "Dark Salmon",
    "Dark Sea Green",
    "Dark Slate Blue",
    "Dark Slate Gray",
    "Dark Slate Grey",
    "Dark Turquoise",
    "Dark Violet",
    "Deep Pink",
    "Deep Sky Blue",
    "Dim Gray",
    "Dodger Blue",
    "Fire Brick",
    "Floral White",
    "Forest Green",
    "Fuchsia",
    "Gainsboro",
    "Ghost White",
    "Gold",
    "Goldenrod",
    "Gray",
    "Green",
    "Green Yellow",
    "Grey",
    "Honeydew",
    "Hot Pink",
    "Indian Red",
    "Indigo",
    "Ivory",
    "Khaki",
    "Lavender",
    "Lavender Blush",
    "Lawn Green",
    "Lemon Chiffon",
    "Light Blue",
    "Light Coral",
    "Light Cyan",
    "Light Goldenrod Yellow",
    "Light Gray",
    "Light Green",
    "Light Grey",
    "Light Pink",
    "Light Salmon",
    "Light Sea Green",
    "Light Sky Blue",
    "Light Slate Gray",
    "Light Slate Grey",
    "Light Steel Blue",
    "Light Yellow",
    "Lime",
    "Lime Green",
    "Linen",
    "Magenta",
    "Maroon",
    "Medium Aquamarine",
    "Medium Blue",
    "Medium Orchid",
    "Medium Purple",
    "Medium Sea Green",
    "Medium Slate Blue",
    "Medium Spring Green",
    "Medium Turquoise",
    "Medium Violet Red",
    "Midnight Blue",
    "Mint Cream",
    "Misty Rose",
    "Moccasin",
    "Navajo White",
    "Navy",
    "Old Lace",
    "Olive",
    "Olive Drab",
    "Orange",
    "Orange Red",
    "Orchid",
    "Pale Goldenrod",
    "Pale Green",
    "Pale Turquoise",
    "Pale Violet Red",
    "Papaya Whip",
    "Peach Puff",
    "Peru",
    "Pink",
    "Plum",
    "Powder Blue",
    "Purple",
    "Rebeccapurple",
    "Red",
    "Rosy Brown",
    "Royal Blue",
    "Saddle Brown",
    "Salmon",
    "Sandy Brown",
    "Sea Green",
    "Seashell",
    "Sienna",
    "Silver",
    "Sky Blue",
    "Slate Blue",
    "Slate Gray",
    "Slate Grey",
    "Snow",
    "Spring Green",
    "Steel Blue",
    "Tan",
    "Teal",
    "Thistle",
    "Tomato",
    "Turquoise",
    "Violet",
    "Wheat",
    "White",
    "White Smoke",
    "Yellow",
    "Yellow Green"
]

patterns = [
    "Argyle",
    "Chevron",
    "Checkered",
    "Damask",
    "Dots",
    "Floral",
    "Gingham",
    "Geometric",
    "Herringbone",
    "Houndstooth",
    "Ikat",
    "Leopard Print",
    "Marble",
    "Mosaic",
    "Ombre",
    "Paisley",
    "Patchwork",
    "Plaid",
    "Quatrefoil",
    "Seersucker",
    "Spiral",
    "Squares",
    "Stars",
    "Stripes",
    "Swirl",
    "Tartan",
    "Toile",
    "Trellis",
    "Tropical",
    "Watercolor",
    "Woodgrain",
    "Zigzag"
]

for i in range(10):
    with open(f'wrapper{i}{extension}', 'w') as f:
        f.write(f"INSERT INTO wrappers (length, width, color, complementaryColor, pattern) VALUES \n")
        for j in range(100000):
            width = randint(1, 30)
            f.write(f"({randint(width, 100 + width)}, {width}, '{choice(colors)}', '{choice(colors)}', '{choice(patterns)}'){';' if j == 99999 else ','}\n")

            