# Specify the base image for the backend
FROM node:18
WORKDIR /app
# Copy the backend source code
COPY ./backend/package.json ./backend/
COPY ./backend/package-lock.json ./backend/
RUN npm install --prefix ./backend
COPY ./backend ./backend

# Build the backend
RUN npm run build --prefix ./backend

# Copy the frontend source code
COPY ./frontend/package.json ./frontend/
COPY ./frontend/package-lock.json ./frontend/
RUN npm install --prefix ./frontend
COPY ./frontend ./frontend

# Build the frontend
RUN npm run build --prefix ./frontend

# Install dependencies for serving both applications
RUN npm install -g serve
RUN npm install -g concurrently

# Expose ports if necessary (e.g., if backend and frontend use different ports)
# backend: 80
EXPOSE 80 
# frontend: 3000
EXPOSE 3000

# Command to start both applications
CMD concurrently "npm start --prefix ./backend" "serve -s frontend/build -l 3000"
