from random import choice, randint

extension = '.session.sql'

import random

companyAdjectives = [
    "Agile",
    "Bold",
    "Brilliant",
    "Creative",
    "Dynamic",
    "Elite",
    "Energetic",
    "Fresh",
    "Global",
    "Impactful",
    "Innovative",
    "Inspiring",
    "Intelligent",
    "Modern",
    "Nimble",
    "Optimal",
    "Passionate",
    "Powerful",
    "Proactive",
    "Professional",
    "Reliable",
    "Revolutionary",
    "Savvy",
    "Smart",
    "Smooth",
    "Sustainable",
    "Synergetic",
    "Tech",
    "Top",
    "Trusted",
    "Up",
    "Vibrant",
    "Visionary",
    "Wise",
    "Worldwide",
    "Xcellent",
    "Young",
    "Zealous",
    "Zesty",
    "Zingy"
]

companyNouns = [
    "Academy",
    "Agency",
    "Alliance",
    "Associates",
    "Capital",
    "Co",
    "Collective",
    "Commerce",
    "Company",
    "Corporation",
    "Creative",
    "Digital",
    "Enterprise",
    "Group",
    "Industries",
    "Innovation",
    "Institute",
    "International",
    "Investments",
    "Lab",
    "Labs",
    "Media",
    "Network",
    "Partners",
    "Solutions",
    "Software",
    "Studios",
    "Systems",
    "Technologies",
    "Technology",
    "Ventures",
    "Works",
    "World",
    "Worldwide",
    "Xperts",
    "Yard",
    "Yardstick",
    "Yarn",
    "Zap",
    "Zen"
]

companySuffixes = [
    "AG",
    "BV",
    "Co",
    "Corp",
    "GmbH",
    "Inc",
    "LLC",
    "Ltd",
    "NV",
    "SA",
    "SARL",
    "SAS",
    "SE",
    "SL",
    "SRL",
    "SpA",
    "Sdn Bhd",
    "VEB",
    "Zrt",
]

companyPrefixes = [
    "A",
    "Alpha",
    "Apex",
    "Astra",
    "Aurora",
    "B",
    "Beta",
    "C",
    "Capital",
    "Centric",
    "Cloud",
    "Com",
    "Compass",
    "Con",
    "Connect",
    "Core",
    "D",
    "Data",
    "Digital",
    "Direct",
    "E",
    "Eagle",
    "East",
    "Easy",
    "Edge",
    "Elevate",
    "Elite",
    "Epic",
    "Equity",
    "Essential",
    "Eternal",
    "Ever",
    "Everest",
    "Evolve",
    "Ex",
    "Excel",
    "Expert",
    "Express",
    "F",
    "Fast",
    "First",
    "Focus",
    "Forward",
    "Front",
    "Future",
    "G",
    "Global",
    "Gold",
    "Golden",
    "Grand",
    "Great",
    "Green",
    "H",
    "Harmony",
    "High",
    "Horizon",
    "Hyper",
    "I",
    "Imperial",
    "In",
    "Infinite",
    "Innova",
    "Innovate",
    "Inspire",
    "Insta",
    "Intelli",
    "Inter",
    "J",
    "K",
    "Key",
    "L",
    "Lead",
    "M",
    "Macro",
    "Master",
    "Max",
    "Mega",
    "Meta",
    "Metro",
    "Micro",
    "Millenium",
    "Momentum",
    "N",
    "National",
    "Net",
    "New",
    "Next",
    "Noble",
    "North",
    "O",
    "Omega",
    "Omni",
    "One",
    "Open",
    "Optima",
    "Optimum",
    "P",
    "Peak",
    "Perfect",
    "Pinnacle",
    "Pioneer",
    "Plus",
    "Point",
    "Power",
    "Premium",
    "Prime",
    "Pro",
    "Progress",
    "Q",
    "R",
    "Rapid",
    "Red",
    "S",
    "Silver",
    "Simple",
    "Sky",
    "Smart",
    "Soft",
    "Spectrum",
    "Star",
    "Stellar",
    "Super",
    "Supreme",
    "T",
    "Tech",
    "Terra",
    "Top",
    "U",
    "Ultra",
    "Union",
    "United",
    "Universal",
    "V",
    "Vantage",
    "Vega",
    "Venture",
    "Vertex",
    "Vista",
    "W",
    "West",
    "White",
    "X",
    "Y",
    "Z",
    "Zen",
    "Zero",
    "Zeta",
    "Zing",
    "Zion",
    "Zodiac",
    "Zone",
    "Zoo",
    "Zoom"
]

emailProviders = [
    "gmail.com",
    "yahoo.com",
    "hotmail.com",
    "outlook.com",
    "aol.com",
    "protonmail.com",
    "icloud.com",
    "zoho.com",
    "mail.com",
    "yandex.com",
    "gmx.com",
    "inbox.com",
    "tutanota.com",
    "fastmail.com",
    "hushmail.com",
]

streetNames = [
    "Main Street",
    "High Street",
    "Broadway",
    "Park Avenue",
    "Maple Street",
    "Elm Street",
    "Church Street",
    "Washington Street",
    "First Street",
    "Second Street",
    "Third Street",
    "Fourth Street",
    "Fifth Avenue",
    "Sixth Avenue",
    "Seventh Avenue",
    "Eighth Avenue",
    "Ninth Avenue",
    "Tenth Avenue",
    "Bond Street",
    "Canal Street",
    "Lexington Avenue",
    "Madison Avenue",
    "Fifth Avenue",
    "Wall Street",
    "Bourbon Street",
    "Rodeo Drive",
    "Sunset Boulevard",
    "Abbey Road",
    "Oxford Street",
    "Regent Street",
    "The Mall",
    "Kings Road",
    "Queen Street",
    "Collins Street",
    "Swanston Street",
    "Flinders Street",
    "Champs-Élysées",
    "Rue de Rivoli",
    "Kurfürstendamm",
    "Friedrichstraße",
    "Unter den Linden",
    "Potsdamer Platz",
    "Gran Via",
    "Las Ramblas",
    "Via del Corso",
    "Avinguda Diagonal",
    "Nevsky Prospekt",
    "Tverskaya Street",
    "Princes Street",
    "Royal Mile",
    "Sauchiehall Street",
    "Rundle Street",
    "Gouger Street",
    "Smith Street",
    "Brunswick Street",
    "Swan Street",
    "Chapel Street",
    "Bridge Road",
    "Toorak Road",
    "Collins Avenue",
    "Lincoln Road",
    "Ocean Drive",
    "Biscayne Boulevard",
    "Wilshire Boulevard",
    "Rodeo Drive",
    "Sunset Strip",
    "Santa Monica Boulevard",
    "Melrose Avenue",
    "Hollywood Boulevard",
    "Venice Boulevard",
    "La Cienega Boulevard",
    "La Brea Avenue",
    "Figueroa Street",
    "Sepulveda Boulevard",
    "Beverly Boulevard",
    "Mulholland Drive",
    "Sunset Plaza Drive",
    "Coldwater Canyon Drive",
    "Mount Olympus Drive",
    "Whitley Heights Terrace",
    "Echo Park Avenue",
    "Silver Lake Boulevard",
    "Hancock Park Terrace",
    "Los Feliz Boulevard",
    "Mulholland Highway",
    "Pacific Coast Highway",
    "Ventura Boulevard",
    "Sherman Way",
    "Lankershim Boulevard",
    "Mulholland Drive",
    "Hollywood Hills Road",
    "Benedict Canyon Drive",
    "Laurel Canyon Boulevard",
    "Wonderland Avenue",
    "San Vicente Boulevard",
    "Santa Monica Boulevard",
    "Brentwood Terrace",
    "Roxbury Drive",
    "Mandeville Canyon Road",
    "Sunset Ridge Drive",
    "Coldwater Canyon Avenue",
    "Beverly Glen Boulevard",
    "Nichols Canyon Road",
]

usStates = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
]

def generate_phone_number():
    prefix = "07"
    prefix_digits = str(random.randint(0, 99)).zfill(2)
    middle_digits = str(random.randint(0, 999)).zfill(3)
    last_digits = str(random.randint(0, 999)).zfill(3)
    separator = " " if random.random() > 0.5 else "-"
    second_separator = "" if random.random() > 0.5 else separator
    return f"{prefix}{prefix_digits}{separator}{middle_digits}{second_separator}{last_digits}"

def generate_address():
    number = random.randint(1, 10000)
    street = choice(streetNames)
    state = choice(usStates)
    return f"{number} {street}, {state} USA"

import random

def generateCompany():
    prefix = random.choice(companyPrefixes)
    adjective = random.choice(companyAdjectives)
    noun = random.choice(companyNouns)
    suffix = random.choice(companySuffixes)
    number = random.randint(0, 999)

    hasCustomMail = random.random() > 0.8
    hasPrefix = random.random() > 0.4
    hasSuffix = random.random() > 0.1
    hasNumber = random.random() > 0.5

    name = ""
    if hasPrefix:
        name += prefix + " "
    name += adjective + " " + noun
    if hasNumber:
        name += " " + str(number)
    if hasSuffix:
        name += " " + suffix

    companyEmail = adjective.lower() + noun.lower() + "@"
    if hasCustomMail:
        companyEmail += noun.lower() + ".com"
    else:
        companyEmail += random.choice(emailProviders)

    # "({randint(width, 100 + width)}, {width}, '{choice(colors)}', '{choice(colors)}', '{choice(patterns)}'){';' if j == 99999 else ','}\n"
    return f"('{name}', '{generate_address()}', '{generate_phone_number()}', '{companyEmail}'){';' if j == 99999 else ','}\n"



for i in range(10):
    with open(f'supplier{i}{extension}', 'w') as f:
        f.write(f"INSERT INTO suppliers (name, address, phone, email) VALUES\n")
        for j in range(100000):
            f.write(generateCompany())

            